### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by typometre** [threadi/download-list-preview#1]
Hi,
Thanks but sadly the plugin doesn't install.

L’extension n’a pas pu être activée, car elle a déclenché une erreur fatale.

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class downloadlist\Helper does not have a method "add_generic_iconset" in /home/*****/wp-includes/class-wp-hook.php:324 Stack trace: #0 /home/*****/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #1 /home/rohe3252/*****/wp-includes/plugin.php(517): WP_Hook->do_action() #2 /home/*****/wp-admin/plugins.php(196): do_action() #3 {main} thrown in /home/*****/wp-includes/class-wp-hook.php on line 324

**Comment by threadi** [comment]
Thanks for the hint. I made the plugin compatible with the current version of the main plugin and made some optimizations. You can now find the release as a separate ZIP here: https://github.com/threadi/download-list-preview/releases/tag/1.0.2
